### ISSUE TITLE
Repository information for Maven ecosystem

### ISSUE THREAD

**Issue by ctron** [gcmurphy/osv#29]
According to the specification, the `Maven` ecosystem can carry an additional repository URL: https://ossf.github.io/osv-schema/#affectedpackage-field

> The ecosystem string might optionally have a :<REMOTE-REPO-URL> suffix to denote the remote repository URL that best represents the source of truth for this package, without a trailing slash (e.g. Maven:https://maven.google.com). If this is omitted, this is assumed to be the Maven Central repository (https://repo.maven.apache.org/maven2).

Right now the `Ecosystem::Maven` variant doesn't support this.

**Comment by gcmurphy** [comment]
Good catch. In hindsight it would be nice to have a more generic solution for the versioned ecosystems like Debian and Alpine too.
