### ISSUE TITLE
`published` field is not mandatory

### ISSUE THREAD

**Issue by ctron** [gcmurphy/osv#50]
While the `modified` field is mandatory, the `published` field is not: https://github.com/ossf/osv-schema/blob/00aefbd25076f73c3cf5357759544b2957e0e1a1/validation/schema.json#L17-L19

For example: https://github.com/pypa/advisory-database/blob/main/vulns/cipherbcrypt/PYSEC-2024-55.yaml

**Comment by gcmurphy** [comment]
fixed by #51. thanks for your contribution!
